#!/bin/bash
# start-bt-bridge.sh - generated by aprs-tui wizard
# Bridges BT serial to KISS TCP port 8001
# Usage: ./start-bt-bridge.sh

DEVICE="/dev/cu.TNC4Mobilinkd"
PORT=8001

echo "Starting BT bridge: $DEVICE -> TCP port $PORT"

while true; do
    socat TCP-LISTEN:$PORT,reuseaddr,fork OPEN:$DEVICE,rawer
    echo "Bridge disconnected, restarting in 3s..."
    sleep 3
done
