#!/bin/bash
# setup-direwolf-pi.sh
# Installs and configures Direwolf on Raspberry Pi Zero W2 (32-bit)
# with DigiRig Mobile as the sound card interface.
#
# Usage: curl -sSL <url> | bash
#   or:  chmod +x setup-direwolf-pi.sh && ./setup-direwolf-pi.sh
#
# What this does:
#   1. Installs build dependencies
#   2. Builds Direwolf from source (latest stable)
#   3. Detects the DigiRig USB sound card
#   4. Generates direwolf.conf with KISS TCP on port 8001
#   5. Creates a systemd service for auto-start
#   6. Publishes mDNS so the APRS TUI can discover it automatically

set -e

echo "============================================"
echo "  Direwolf + DigiRig Setup for Raspberry Pi"
echo "============================================"
echo

# --- Check we're on a Pi ---
if [ ! -f /proc/cpuinfo ] || ! grep -qi "raspberry\|BCM" /proc/cpuinfo 2>/dev/null; then
    echo "[!] This script is designed for Raspberry Pi."
    echo "    Proceed anyway? (y/N)"
    read -r yn
    [ "$yn" != "y" ] && exit 1
fi

ARCH=$(uname -m)
echo "Platform: $(cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d'"' -f2)"
echo "Architecture: $ARCH"
echo

# --- Install dependencies ---
echo "[1/7] Installing build dependencies..."
sudo apt-get update -qq
sudo apt-get install -y -qq \
    git gcc g++ make cmake \
    libasound2-dev libudev-dev \
    avahi-daemon avahi-utils \
    socat screen \
    python3 python3-venv python3-pip

echo "  Done."

# --- Build Direwolf from source ---
echo
echo "[2/7] Building Direwolf from source..."
DIREWOLF_DIR="$HOME/direwolf"

if command -v direwolf &>/dev/null; then
    EXISTING_VER=$(direwolf -t 0 -h 2>&1 | head -1 || echo "installed" || echo "unknown")
    echo "  Direwolf already installed: $EXISTING_VER"
    echo "  Rebuild? (y/N)"
    read -r rebuild
    if [ "$rebuild" != "y" ]; then
        echo "  Skipping build."
        SKIP_BUILD=1
    fi
fi

if [ "${SKIP_BUILD:-}" != "1" ]; then
    rm -rf "$DIREWOLF_DIR"
    git clone --depth 1 https://github.com/wb2osz/direwolf.git "$DIREWOLF_DIR"
    cd "$DIREWOLF_DIR"
    mkdir -p build && cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
    make -j$(nproc)
    sudo make install
    cd "$HOME"
    echo "  Direwolf installed: $(direwolf -t 0 -h 2>&1 | head -1 || echo "installed")"
fi

# --- Detect DigiRig sound card ---
echo
echo "[3/7] Detecting DigiRig USB sound card..."

echo "  Available sound cards:"
cat /proc/asound/cards
echo

# Look for USB/C-Media/PnP sound card - extract the ALSA name (not card number)
# Card numbers change across reboots, but names like "Device" are stable.
DIGIRIG_NAME=""
while IFS= read -r line; do
    # Extract card name from lines like " 1 [Device   ]: USB-Audio ..."
    card_name=$(echo "$line" | sed -n 's/.*\[\([^]]*\)\].*/\1/p' | tr -d ' ')
    if [ -z "$card_name" ]; then
        continue
    fi
    if echo "$line" | grep -qi "USB\|C-Media\|DigiRig\|PnP"; then
        DIGIRIG_NAME="$card_name"
        echo "  Detected DigiRig: [$card_name]"
    fi
done < /proc/asound/cards

if [ -z "$DIGIRIG_NAME" ]; then
    echo "  [!] Could not auto-detect DigiRig."
    echo "  Enter the ALSA card name from the list above (e.g., Device):"
    read -r manual_name
    DIGIRIG_NAME="${manual_name:-Device}"
fi

# Use card name instead of number - survives reboots
ALSA_DEVICE="plughw:${DIGIRIG_NAME},0"
echo "  Using ALSA device: $ALSA_DEVICE (stable across reboots)"

# --- Detect DigiRig serial port (for PTT) ---
echo
echo "[4/7] Detecting DigiRig serial port for PTT..."

DIGIRIG_SERIAL=""
for dev in /dev/ttyUSB* /dev/ttyACM*; do
    if [ -e "$dev" ]; then
        # Check if it's associated with a USB audio/serial combo (DigiRig pattern)
        DIGIRIG_SERIAL="$dev"
        echo "  Found serial port: $dev"
        break
    fi
done

if [ -z "$DIGIRIG_SERIAL" ]; then
    echo "  [!] No serial port found for PTT."
    echo "  DigiRig PTT will use VOX mode instead."
    PTT_METHOD="VOX"
else
    PTT_METHOD="$DIGIRIG_SERIAL RTS"
fi

# --- Generate direwolf.conf ---
echo
echo "[5/7] Generating direwolf.conf..."

CALLSIGN="${APRS_CALLSIGN:-N0CALL}"
echo "  Enter your callsign [$CALLSIGN]:"
read -r input_call
CALLSIGN="${input_call:-$CALLSIGN}"
CALLSIGN=$(echo "$CALLSIGN" | tr '[:lower:]' '[:upper:]')

CONF_DIR="$HOME/.config/direwolf"
CONF_FILE="$CONF_DIR/direwolf.conf"
mkdir -p "$CONF_DIR"

cat > "$CONF_FILE" << DWEOF
# direwolf.conf - Generated by APRS TUI setup script
# Platform: Raspberry Pi Zero W2 + DigiRig Mobile
# Date: $(date -u +"%Y-%m-%d %H:%M UTC")

# -----------------------------------------------
# Audio
# -----------------------------------------------
ADEVICE $ALSA_DEVICE $ALSA_DEVICE
ARATE 44100
ACHANNELS 1

# -----------------------------------------------
# Channel 0 - 1200 baud AFSK (VHF APRS)
# -----------------------------------------------
CHANNEL 0
MYCALL ${CALLSIGN}-10
MODEM 1200

# PTT control via DigiRig
PTT $PTT_METHOD

# -----------------------------------------------
# KISS TCP interface (for APRS TUI)
# -----------------------------------------------
KISSPORT 8001

# -----------------------------------------------
# APRS Digipeater (optional - uncomment to enable)
# -----------------------------------------------
# DIGIPEAT 0 0 ^WIDE[3-7]-[1-7]$|^TEST$ ^WIDE[12]-[12]$ TRACE
# DIGIPEAT 0 0 ^WIDE[3-7]-[1-7]$|^TEST$ ^WIDE[12]-[12]$

# -----------------------------------------------
# APRS Internet Gateway (optional - uncomment to enable)
# -----------------------------------------------
# IGSERVER noam.aprs2.net
# IGLOGIN ${CALLSIGN}-10 -1

# -----------------------------------------------
# Beaconing (optional - uncomment and set position)
# -----------------------------------------------
# PBEACON delay=1 every=30 overlay=S symbol="digi" lat=00.0000 long=000.0000 power=1 height=20 gain=2 comment="Direwolf on Pi"

DWEOF

echo "  Config written to $CONF_FILE"

# --- Open firewall for KISS TCP ---
echo
echo "[6/8] Opening firewall for KISS TCP port 8001..."

if command -v ufw &>/dev/null; then
    sudo ufw allow 8001/tcp comment "Direwolf KISS TCP" 2>/dev/null && \
        echo "  [OK] ufw: port 8001 opened" || \
        echo "  [!] ufw rule may already exist"
elif command -v nft &>/dev/null; then
    # Debian trixie+ uses nftables - ensure table and chain exist first
    sudo nft add table inet filter 2>/dev/null
    sudo nft add chain inet filter input '{ type filter hook input priority 0; policy accept; }' 2>/dev/null
    sudo nft add rule inet filter input tcp dport 8001 accept 2>/dev/null && \
        echo "  [OK] nftables: port 8001 opened" || \
        echo "  [!] nftables rule may already exist"
    # Persist across reboots
    if command -v nft &>/dev/null; then
        sudo nft list ruleset | sudo tee /etc/nftables.conf >/dev/null 2>&1
        sudo systemctl enable nftables 2>/dev/null
        echo "  [OK] nftables rules saved for reboot"
    fi
elif command -v iptables &>/dev/null; then
    if sudo iptables -C INPUT -p tcp --dport 8001 -j ACCEPT 2>/dev/null; then
        echo "  Port 8001 already open in iptables"
    else
        sudo iptables -A INPUT -p tcp --dport 8001 -j ACCEPT
        echo "  [OK] iptables: port 8001 opened"
    fi
else
    echo "  [OK] No firewall tool found (ufw/nft/iptables) - port 8001 should be open by default"
fi

# --- Create systemd service ---
echo
echo "[7/8] Creating systemd service..."

UNIT_FILE="/etc/systemd/system/direwolf.service"
sudo tee "$UNIT_FILE" > /dev/null << SVCEOF
[Unit]
Description=Direwolf APRS TNC
After=sound.target network.target
Wants=avahi-daemon.service

[Service]
Type=simple
User=$USER
ExecStart=/usr/local/bin/direwolf -c $CONF_FILE -t 0
Restart=on-failure
RestartSec=5

# Wait for USB sound card to initialize
ExecStartPre=/bin/sleep 3

[Install]
WantedBy=multi-user.target
SVCEOF

sudo systemctl daemon-reload
sudo systemctl enable direwolf
echo "  Service created and enabled."
echo "  Start now? (Y/n):"
read -r start_now
if [ "${start_now:-y}" != "n" ]; then
    sudo systemctl start direwolf
    sleep 2
    if systemctl is-active --quiet direwolf; then
        echo "  [OK] Direwolf is running!"
    else
        echo "  [!] Direwolf failed to start. Check: journalctl -u direwolf -n 20"
    fi
fi

# --- Publish mDNS for auto-discovery ---
echo
echo "[8/8] Setting up mDNS auto-discovery..."

MDNS_UNIT="/etc/systemd/system/direwolf-mdns.service"
sudo tee "$MDNS_UNIT" > /dev/null << MDNSEOF
[Unit]
Description=Direwolf KISS TNC mDNS advertisement
After=avahi-daemon.service direwolf.service
Requires=avahi-daemon.service

[Service]
Type=simple
ExecStart=/usr/bin/avahi-publish-service "Direwolf KISS on $(hostname)" _kiss-tnc._tcp 8001
Restart=on-failure

[Install]
WantedBy=multi-user.target
MDNSEOF

sudo systemctl daemon-reload
sudo systemctl enable direwolf-mdns
sudo systemctl start direwolf-mdns
echo "  mDNS advertising _kiss-tnc._tcp on port 8001"

# --- Summary ---
echo
echo "============================================"
echo "  Setup Complete!"
echo "============================================"
echo
echo "  Callsign:    $CALLSIGN-10"
echo "  Sound card:  $ALSA_DEVICE (DigiRig)"
echo "  PTT:         $PTT_METHOD"
echo "  KISS TCP:    port 8001"
echo "  Config:      $CONF_FILE"
echo "  mDNS:        _kiss-tnc._tcp (auto-discoverable)"
echo
echo "  Commands:"
echo "    sudo systemctl status direwolf     # Check status"
echo "    sudo systemctl restart direwolf    # Restart"
echo "    journalctl -u direwolf -f          # Live logs"
echo "    direwolf -c $CONF_FILE             # Run in foreground (debug)"
echo
echo "  From your laptop, run the APRS TUI:"
echo "    ./start.sh"
echo "  It will auto-discover this Direwolf server via mDNS,"
echo "  or connect manually to $(hostname).local:8001"
echo
